### ISSUE TITLE
issue with 4.0.4beta

### ISSUE THREAD

**Issue by phracek** [phracek/rebase-helper#105] opened 2015-05-26 12:06 UTC
rebase-helper wrongly setup version in case of tiff-4.0.4 beta.
In setup is mentioned:
%setup -q -n tiff-{version} which is tiff-4.0.4
but it should be tiff-4.0.4beta instead.

I suggest to look at the archive how the archive is really called and update %setup macro.

**Comment by thozza** [comment] 2015-05-26 16:10
duplicate of #82

**Closed by thozza** 2015-05-26 16:10 UTC
Labels: archive files, bug, duplicate, SPEC files
