### ISSUE TITLE
after rebasing systemd no patches applied and rebase-helper tracebacks

### ISSUE THREAD

**Issue by lnykryn** [phracek/rebase-helper#73] opened 2014-10-16 09:06 UTC
[lnykryn@notas systemd(rhel-7.1)]$ python ~/dev/upstream/rebase-helper/rebase-helper.py 216
Downloading sources from URL http://www.freedesktop.org/software/systemd/systemd-216.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 3528k  100 3528k    0     0   323k      0  0:00:10  0:00:10 --:--:--  384k
Building SRPM
Traceback (most recent call last):
  File "/home/lnykryn/dev/upstream/rebase-helper/rebase-helper.py", line 46, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/lnykryn/dev/upstream/rebase-helper/rebase-helper.py", line 35, in main
    app.run()
  File "/mnt/fedora/home/lnykryn/dev/upstream/rebase-helper/rebasehelper/application.py", line 401, in run
    self.build_packages()
  File "/mnt/fedora/home/lnykryn/dev/upstream/rebase-helper/rebasehelper/application.py", line 345, in build_packages
    files = BuildLogAnalyzer.parse_log(os.path.join(results_dir, 'RPM'), 'build.log')
  File "/mnt/fedora/home/lnykryn/dev/upstream/rebase-helper/rebasehelper/build_log_analyzer.py", line 43, in parse_log
    return log_dictionary[log_name](os.path.join(dir_name, log_name))
  File "/mnt/fedora/home/lnykryn/dev/upstream/rebase-helper/rebasehelper/build_log_analyzer.py", line 61, in _parse_build_log
    section = cls._find_section(log_name, missing_reg, e_reg)
  File "/mnt/fedora/home/lnykryn/dev/upstream/rebase-helper/rebasehelper/build_log_analyzer.py", line 104, in _find_section
    with open(log_name, 'r') as f:
IOError: [Errno 2] No such file or directory: '/mnt/fedora/home/lnykryn/dev/rhel/systemd/rebase-helper-results/old/RPM/build.log'

[lnykryn@notas systemd(rhel-7.1)]$ cat rebase-helper-results/rebase-helper-debug.log 
2014-10-16 10:59:52,980 DEBUG Application: argument passed as a new source is a version
2014-10-16 10:59:52,980 DEBUG SpecFile: Updating version in SPEC from '208' with '216'
2014-10-16 10:59:52,981 DEBUG SpecFile: Writing SPEC file '/mnt/fedora/home/lnykryn/dev/rhel/systemd/rebase-helper-results/systemd.spec' to the disc
2014-10-16 10:59:53,637 INFO Downloading sources from URL http://www.freedesktop.org/software/systemd/systemd-216.tar.xz
2014-10-16 10:59:53,637 DEBUG ProcessHelper.run_subprocess: cmd=['curl', '-H', 'Pragma:', '-o', 'systemd-216.tar.xz', '-R', '-S', '--fail', 'http://www.freedesktop.org/software/systemd/systemd-216.tar.xz'], cwd=None, env=None, input=None, output=None, shell=False
2014-10-16 11:00:04,556 DEBUG ProcessHelper.run_subprocess: subprocess exited with return code 0
2014-10-16 11:00:04,567 DEBUG Archive: Extracting '/mnt/fedora/home/lnykryn/dev/rhel/systemd/systemd-208.tar.xz' into '/mnt/fedora/home/lnykryn/dev/rhel/systemd/rebase-helper-workspace/old_sources'
2014-10-16 11:00:05,363 DEBUG Archive: Extracting '/mnt/fedora/home/lnykryn/dev/rhel/systemd/systemd-216.tar.xz' into '/mnt/fedora/home/lnykryn/dev/rhel/systemd/rebase-helper-workspace/new_sources'
2014-10-16 11:00:06,511 DEBUG Patch: Patching source by patch tool patch
2014-10-16 11:00:06,511 DEBUG Builder: Building sources using 'mock'
2014-10-16 11:00:06,511 DEBUG TemporaryEnvironment: Created environment in '/tmp/rebase-helper-AkNZlv'
2014-10-16 11:00:06,511 DEBUG MockTemporaryEnvironment: Creating '/tmp/rebase-helper-AkNZlv/SOURCES'
2014-10-16 11:00:06,511 DEBUG MockTemporaryEnvironment: Creating '/tmp/rebase-helper-AkNZlv/SPECS'
2014-10-16 11:00:06,511 DEBUG MockTemporaryEnvironment: Creating '/tmp/rebase-helper-AkNZlv/RESULTS'
2014-10-16 11:00:06,512 DEBUG BuildTemporaryEnvironment: Copying '/mnt/fedora/home/lnykryn/dev/rhel/systemd/60-alias-kmsg.rules' to '/tmp/rebase-helper-AkNZlv/SOURCES'
2014-10-16 11:00:06,512 DEBUG BuildTemporaryEnvironment: Copying '/mnt/fedora/home/lnykryn/dev/rhel/systemd/rc.local' to '/tmp/rebase-helper-AkNZlv/SOURCES'
2014-10-16 11:00:06,512 DEBUG BuildTemporaryEnvironment: Copying '/mnt/fedora/home/lnykryn/dev/rhel/systemd/yum-protect-systemd.conf' to '/tmp/rebase-helper-AkNZlv/SOURCES'
2014-10-16 11:00:06,512 DEBUG BuildTemporaryEnvironment: Copying '/mnt/fedora/home/lnykryn/dev/rhel/systemd/listen.conf' to '/tmp/rebase-helper-AkNZlv/SOURCES'
2014-10-16 11:00:06,512 DEBUG BuildTemporaryEnvironment: Copying '/mnt/fedora/home/lnykryn/dev/rhel/systemd/systemd-sysv-convert' to '/tmp/rebase-helper-AkNZlv/SOURCES'
2014-10-16 11:00:06,512 DEBUG BuildTemporaryEnvironment: Copying '/mnt/fedora/home/lnykryn/dev/rhel/systemd/99-default-disable.preset' to '/tmp/rebase-helper-AkNZlv/SOURCES'
2014-10-16 11:00:06,512 DEBUG BuildTemporaryEnvironment: Copying '/mnt/fedora/home/lnykryn/dev/rhel/systemd/systemd-208.tar.xz' to '/tmp/rebase-helper-AkNZlv/SOURCES'
2014-10-16 11:00:06,514 DEBUG BuildTemporaryEnvironment: Copying '/mnt/fedora/home/lnykryn/dev/rhel/systemd/systemd.spec' to '/tmp/rebase-helper-AkNZlv/SPECS/systemd.spec'
2014-10-16 11:00:06,514 INFO Building SRPM
2014-10-16 11:00:06,514 DEBUG ProcessHelper.run_subprocess: cmd=['mock', '--buildsrpm', '--spec', '/tmp/rebase-helper-AkNZlv/SPECS/systemd.spec', '--sources', '/tmp/rebase-helper-AkNZlv/SOURCES', '--resultdir', '/tmp/rebase-helper-AkNZlv/RESULTS'], cwd=None, env=None, input=None, output=/tmp/rebase-helper-AkNZlv/RESULTS/mock_output.log, shell=False
2014-10-16 11:04:04,443 DEBUG ProcessHelper.run_subprocess: subprocess exited with return code 1
2014-10-16 11:04:04,444 DEBUG BuildTemporaryEnvironment: Copying 'log' '/tmp/rebase-helper-AkNZlv/RESULTS/root.log' to '/mnt/fedora/home/lnykryn/dev/rhel/systemd/rebase-helper-results/old/SRPM'
2014-10-16 11:04:04,444 DEBUG BuildTemporaryEnvironment: Copying 'log' '/tmp/rebase-helper-AkNZlv/RESULTS/build.log' to '/mnt/fedora/home/lnykryn/dev/rhel/systemd/rebase-helper-results/old/SRPM'
2014-10-16 11:04:04,445 DEBUG BuildTemporaryEnvironment: Copying 'log' '/tmp/rebase-helper-AkNZlv/RESULTS/state.log' to '/mnt/fedora/home/lnykryn/dev/rhel/systemd/rebase-helper-results/old/SRPM'
2014-10-16 11:04:04,445 DEBUG BuildTemporaryEnvironment: Copying 'log' '/tmp/rebase-helper-AkNZlv/RESULTS/mock_output.log' to '/mnt/fedora/home/lnykryn/dev/rhel/systemd/rebase-helper-results/old/SRPM'
2014-10-16 11:04:04,445 DEBUG TemporaryEnvironment: Exit callback executed successfully
2014-10-16 11:04:04,446 DEBUG TemporaryEnvironment: Destroyed environment in '/tmp/rebase-helper-AkNZlv'
2014-10-16 11:04:04,446 DEBUG Build failed 0. Building SRPM failed!

**Comment by phracek** [comment] 2015-02-27 14:04
the issue is basically solved by commit https://github.com/phracek/rebase-helper/commit/0923c17c95f06f2c69266d3df9e1849bd231d2cb

Review is needed though

**Comment by phracek** [comment] 2015-07-23 11:10
Issue should be fixed by https://github.com/phracek/rebase-helper/pull/112

**Closed by phracek** 2015-07-23 11:10 UTC
Labels: bug, patches, SPEC files
