### ISSUE TITLE
rebase-helper traceback while rebasing quagga in Fedora

### ISSUE THREAD

**Issue by msekletar** [phracek/rebase-helper#83] opened 2014-12-05 10:12 UTC
Steps to reproduce:

1) clone quagga dist-git repository
2) check out f19 branch
3) download upstream tarball http://download.savannah.gnu.org/releases/quagga/quagga-0.99.22.4.tar.gz to the cloned repository
4) run rebase-helper.py --buildtool rpmbuild quagga-0.99.22.4.tar.gz

Additional information:
Rebase helper output

```
Results directory 'rebase-helper-results' exists, removing it
Workspace directory 'rebase-helper-workspace' exists, removing it
Applying patch '0001-systemd-change-the-WantedBy-target.patch' to 'quagga-0.99.22.1'
Applying patch '0001-systemd-change-the-WantedBy-target.patch' to 'quagga-0.99.22.4'
Building SRPM
Building SRPM finished successfully
Building RPMs
Traceback (most recent call last):
  File "/usr/local/bin/rebase-helper", line 28, in <module>
    sys.exit(CliHelper.run())
  File "/home/msekleta/devel/upstream/rebase-helper/rebasehelper/cli.py", line 129, in run
    app.run()
  File "/home/msekleta/devel/upstream/rebase-helper/rebasehelper/application.py", line 424, in run
    self.build_packages()
  File "/home/msekleta/devel/upstream/rebase-helper/rebasehelper/application.py", line 343, in build_packages
    build_dict.update(builder.build(spec, sources, patches, results_dir, **build_dict))
  File "/home/msekleta/devel/upstream/rebase-helper/rebasehelper/build_helper.py", line 465, in build
    return self._tool.build(*args, **kwargs)
  File "/home/msekleta/devel/upstream/rebase-helper/rebasehelper/build_helper.py", line 421, in build
    rpms = cls._build_rpm(srpm, tmp_dir, tmp_results_dir)
  File "/home/msekleta/devel/upstream/rebase-helper/rebasehelper/build_helper.py", line 362, in _build_rpm
    output=output)
  File "/home/msekleta/devel/upstream/rebase-helper/rebasehelper/utils.py", line 265, in run_subprocess_cwd_env
    out_file.write(line.decode())
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)
```

**Comment by phracek** [comment] 2015-11-03 12:39
I am not able to reproduce it. Closing it. Feel free to reopen it in case of such troubles.

**Closed by phracek** 2015-11-03 12:39 UTC
